name: Build and Run Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --no-cache -t my-spring-app .
      
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 my-spring-app
          sleep 30
          curl --fail http://localhost:8080 || (echo "App not responding" && exit 1)
      
      - name: Tear down
        if: always()
        run: docker stop $(docker ps -q --filter ancestor=my-spring-app)
