name: Build and Run with Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers with Docker Compose
        run: |
          # Build and start the containers in detached mode
          docker-compose up --build -d
          # Give the containers some time to start up
          echo "Waiting for services to be up..."
          sleep 30
          
          curl --fail http://localhost:8080 || (echo "Spring Boot app is not responding" && exit 1)
          
      - name: Tear down
        if: always()
        run: docker-compose down
